version: '3.8'

services:
  app:
    build:
      context: .
    container_name: devmanager-backend
    volumes:
      - .:/var/www/html
    ports:
      - "4040:4040"
    depends_on:
      - db
    environment:
      - DB_HOST=devmanager-db
      - DB_PORT=5432
      - DB_DATABASE=devmanager
      - DB_USERNAME=joao
      - DB_PASSWORD=123456

  db:
    image: postgres:15
    container_name: devmanager-db
    restart: always
    environment:
      POSTGRES_DB: devmanager
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
